# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: prueba 1 

on:
  push:
    branches: [ "main" ]
 

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
       

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: "npm"

    - name: 'Hello World'
      run: echo "Hello World, esto es un workflow de prueba." 

    - name: "Mostrar la fecha"
      run: date

    - name: Mostrar contenido del repo
      run: ls -la

    - name: Simular instalacion Node
      run: npm install --dry-run
